// register.js
export const SWITCH_POP_UP_VISIBILITY = "SWITCH_POP_UP_VISIBILITY";
export const SAVE_REGISTER_ERRORS = "SAVE_REGISTER_ERRORS";
export const REGISTER_START = "REGISTER_START";
export const SUCCESSFULLY_REGISTERED = "SUCCESSFULLY_REGISTERED";
export const REGISTER_ERROR = "REGISTER_ERROR";

// customHeader.js
export const UPDATE_WINDOW_DIMENSIONS = "UPDATE_WINDOW_DIMENSIONS";
