// register.js
export const REGISTER_START = "REGISTER_START";
export const SUCCESSFULLY_REGISTERED = "SUCCESSFULLY_REGISTERED";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const CLOSE_MODAL = "CLOSE_MODAL";

// customHeader.js
export const UPDATE_WINDOW_DIMENSIONS = "UPDATE_WINDOW_DIMENSIONS";
